/* No analytics, network fetches, iframes or remote assets. */
(()=>{'use strict';const $=id=>document.getElementById(id),C=SumiCore,D=SUMI_DATA,storageKey='sumi-reader-v1';let saved={};try{saved=C.safeState(localStorage.getItem(storageKey));}catch{}let favorites=new Set(saved.favorites||[]),progress=saved.progress||{},mode=saved.mode||'page',direction=saved.direction||'rtl',onlyFavorites=false,book=null,page=0,zoom=100,localUrls=[],importToken=0,observer=null,focusReturn=null;
const sample={id:'sample',title:'雨後書店',subtitle:'墨間原創 · CC0 1.0 · 共 6 頁',pages:Array.from({length:6},(_,i)=>({url:`assets/page-${i+1}.svg`,alt:['雨天，小貓在書店窗前等待。','一封送錯的信，帶來尋找月亮的任務。','小貓帶著書穿過濕漉漉的街。','屋頂上的孩子，想把月亮送给外婆。','一本書打開，故事裡的月光照亮小房間。','雨停了，書店多了一位讀者。'][i]})),chapters:[{name:'第 1 話 · 雨中的信',start:0},{name:'第 2 話 · 借一點月光',start:3}]};
function persist(){try{localStorage.setItem(storageKey,JSON.stringify({favorites:[...favorites],progress,mode,direction}));}catch{toast('瀏覽器未允許儲存；這次仍可閱讀，但進度不會保留。');}}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4500);}
function e(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function link(text,url){const a=e('a',text);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function renderCards(){const query=$('search').value.trim().toLocaleLowerCase(),list=D.items.filter(m=>(!onlyFavorites||favorites.has(m.rank))&&[m.title,m.author,m.synopsis].join(' ').toLocaleLowerCase().includes(query));$('cards').replaceChildren();for(const m of list){const article=e('article',undefined,'card'),cover=e('button',undefined,'cover');cover.style.setProperty('--cover',m.color);cover.style.setProperty('--cover-text',m.ink||'#f7f2e6');cover.setAttribute('aria-label',`查看第 ${m.rank} 名 ${m.title} 的介紹`);cover.append(e('span',String(m.rank).padStart(2,'0'),'rank'),e('span',m.title,'cover-title'),e('span','SUMI · WEEKLY SELECTION','cover-note'));cover.onclick=()=>detail(m);const row=e('div',undefined,'card-title-row'),title=e('h3',m.title),fav=e('button',favorites.has(m.rank)?'♥':'♡','favorite');fav.dataset.rank=String(m.rank);fav.setAttribute('aria-label',`${favorites.has(m.rank)?'取消收藏':'收藏'} ${m.title}`);fav.setAttribute('aria-pressed',favorites.has(m.rank));fav.onclick=()=>{favorites.has(m.rank)?favorites.delete(m.rank):favorites.add(m.rank);persist();renderCards();(document.querySelector(`.favorite[data-rank="${m.rank}"]`)||$('show-favorites')).focus();};row.append(title,fav);const official=link('官方閱讀入口 ↗',m.url);official.className='official';article.append(cover,row,e('p',m.author,'author'),official);$('cards').append(article);}$('empty').hidden=!!list.length;$('favorite-count').textContent=favorites.size;$('show-favorites').setAttribute('aria-pressed',onlyFavorites);}
function detail(m){const box=$('detail-content');box.replaceChildren(e('div',`WEEKLY NO. ${String(m.rank).padStart(2,'0')}`,'eyebrow'),e('h2',m.title),e('p',m.author,'muted'),e('p',m.synopsis),e('p',m.readingNote||'官方網站可能僅提供試讀或限定章節，完整內容、價格與地區限制以官方為準。','muted'),link('前往官方閱讀入口 ↗',m.url),e('p','本站沒有這部作品的內頁授權。此連結將開啟外部官方網站。','muted'));$('details').showModal();}
$('ranking-caption').textContent=`ORICON · 作品別銷售週榜 · ${D.ranking.date} · 查核 ${D.ranking.checked}`;const sources=$('source-content');sources.append(e('p',D.ranking.description),link(D.ranking.label+' ↗',D.ranking.url),e('p',`榜單日期：${D.ranking.date} · 資料查核：${D.ranking.checked}。這是人工查核的靜態快照，不是即時自動更新。`,'muted'));if(D.ranking.period)sources.append(e('p','時間範圍說明：'+D.ranking.period));for(const s of D.sources||[]){const p=e('p');p.append(link(s.label+' ↗',s.url));sources.append(p);}
function updateResume(){$('resume-text').textContent=`《雨後書店》· 第 ${C.clamp(progress.sample||0,0,5)+1} / 6 頁 · 原創短篇`;}function releaseLocal(){for(const url of localUrls)URL.revokeObjectURL(url);localUrls=[];}
function openBook(b){focusReturn=document.activeElement;book=b;page=C.clamp(progress[b.id]||0,0,b.pages.length-1);zoom=100;$('reader').hidden=false;document.body.classList.add('reading');$('main').inert=true;document.querySelector('.header').inert=true;document.querySelector('footer').inert=true;$('reader-title').textContent=b.title;$('reader-subtitle').textContent=b.subtitle;$('mode').value=mode;$('direction').value=direction;$('chapter').replaceChildren(...b.chapters.map((c,i)=>new Option(c.name,String(i))));$('page-select').replaceChildren(...b.pages.map((_,i)=>new Option(String(i+1),String(i))));$('page-total').textContent=`/ ${b.pages.length}`;if(location.hash!=='#read')history.pushState(null,'','#read');renderReader();$('reader-back').focus();}
function closeReader(fromHistory=false){if(!book)return;observer?.disconnect();observer=null;book=null;importToken++;$('reader-stage').replaceChildren();releaseLocal();$('reader').hidden=true;document.body.classList.remove('reading');$('main').inert=false;document.querySelector('.header').inert=false;document.querySelector('footer').inert=false;if(!fromHistory&&location.hash==='#read')history.replaceState(null,'','#home');updateResume();focusReturn?.focus();}
function announcePage(){if(!book)return;progress[book.id]=page;persist();$('page-select').value=String(page);$('chapter').value=String(book.chapters.reduce((acc,c,i)=>c.start<=page?i:acc,0));$('prev').disabled=page===0;$('next').disabled=page===book.pages.length-1;$('reader-live').textContent=`第 ${page+1} 頁，共 ${book.pages.length} 頁`;}
function applyZoom(){const base=Math.min(680,$('reader-stage').clientWidth||680);$('reader-stage').style.setProperty('--page-width',`${base*zoom/100}px`);$('zoom-label').value=zoom+'%';$('zoom-out').disabled=zoom<=50;$('zoom-in').disabled=zoom>=200;}
function renderReader(){if(!book)return;observer?.disconnect();observer=null;const stage=$('reader-stage');stage.replaceChildren();const indexes=mode==='scroll'?book.pages.map((_,i)=>i):[page];for(const i of indexes){const img=e('img',undefined,'comic-page');img.src=book.pages[i].url;img.alt=`第 ${i+1} 頁：${book.pages[i].alt}`;img.dataset.index=i;img.decoding='async';img.onerror=()=>toast('圖片無法顯示，請重新匯入原始檔案。');stage.append(img);}applyZoom();announcePage();if(mode==='scroll'){stage.children[page]?.scrollIntoView({block:'start'});observer=new IntersectionObserver(entries=>{if(!book||mode!=='scroll')return;const visible=entries.filter(x=>x.isIntersecting).sort((a,b)=>Math.abs(a.boundingClientRect.top-stage.getBoundingClientRect().top)-Math.abs(b.boundingClientRect.top-stage.getBoundingClientRect().top));if(visible.length){page=Number(visible[0].target.dataset.index);announcePage();}},{root:stage,rootMargin:'0px 0px -70% 0px',threshold:0});for(const child of stage.children)observer.observe(child);}else stage.scrollTo(0,0);}
function navigate(n){if(!book)return;page=C.clamp(n,0,book.pages.length-1);if(mode==='scroll'){$('reader-stage').children[page]?.scrollIntoView({block:'start'});announcePage();}else renderReader();}
function startImport(){importToken++;$('import-status').textContent='';$('pick-files').disabled=false;$('import-dialog').showModal();}
function stopImport(){importToken++;$('import-dialog').close();$('files').value='';$('pick-files').disabled=false;}
function dimensions(url){return new Promise((resolve,reject)=>{const img=new Image();const timer=setTimeout(()=>{img.src='';reject(Error('圖片解碼逾時。'));},10000);img.onload=()=>{clearTimeout(timer);resolve([img.naturalWidth,img.naturalHeight]);};img.onerror=()=>{clearTimeout(timer);reject(Error('圖片無法解碼，可能已損壞。'));};img.src=url;});}
$('files').onchange=async()=>{const token=++importToken;let pending=[];try{const files=C.validateFiles([...$('files').files]);$('pick-files').disabled=true;let pixels=0;const pages=[];for(let i=0;i<files.length;i++){if(token!==importToken)return;const f=files[i],signature=new Uint8Array(await f.arrayBuffer()),type=C.detectType(signature);if(token!==importToken)return;const [headerW,headerH]=C.imageSize(signature,type);if(!headerW||!headerH||headerW*headerH>40000000)throw Error('單張圖片不可超過 4,000 萬像素。');if(pixels+headerW*headerH>160000000)throw Error('圖片總計不可超過 1.6 億像素。');const url=URL.createObjectURL(new Blob([f],{type}));pending.push(url);const[w,h]=await dimensions(url);if(token!==importToken)return;if(!w||!h||w*h>40000000)throw Error('單張圖片不可超過 4,000 萬像素。');pixels+=w*h;if(pixels>160000000)throw Error('圖片總計不可超過 1.6 億像素。');pages.push({url,alt:f.name});$('import-status').textContent=`檢查圖片 ${i+1} / ${files.length}…`;}
if(token!==importToken)return;const id=C.bookKey(files);closeReader();releaseLocal();localUrls=pending;pending=[];$('import-dialog').close();openBook({id,title:'我的本機漫畫',subtitle:`${pages.length} 張圖片 · 不上傳 · 重整後需重新匯入`,pages,chapters:[{name:'本機匯入',start:0}]});}catch(error){if(token===importToken)$('import-status').textContent=error.message;}finally{pending.forEach(url=>URL.revokeObjectURL(url));if(token===importToken){$('pick-files').disabled=false;$('files').value='';}}};
$('sample-open').onclick=$('resume-button').onclick=()=>openBook(sample);$('reader-back').onclick=()=>closeReader();window.addEventListener('popstate',()=>{if($('import-dialog').open)stopImport();if(location.hash!=='#read')closeReader(true);else if(!book){history.replaceState(null,'','#home');toast('本機圖片未保留；請重新開啟漫畫。');}});window.addEventListener('hashchange',()=>{if($('import-dialog').open)stopImport();if(location.hash!=='#read'&&book)closeReader(true);});if(location.hash==='#read')history.replaceState(null,'','#home');
$('prev').onclick=()=>navigate(page-1);$('next').onclick=()=>navigate(page+1);$('page-select').onchange=()=>navigate(Number($('page-select').value));$('chapter').onchange=()=>navigate(book.chapters[Number($('chapter').value)].start);$('mode').onchange=()=>{mode=$('mode').value;persist();renderReader();};$('direction').onchange=()=>{direction=$('direction').value;persist();};$('zoom-in').onclick=()=>{zoom=C.clamp(zoom+25,50,200);applyZoom();};$('zoom-out').onclick=()=>{zoom=C.clamp(zoom-25,50,200);applyZoom();};$('zoom-reset').onclick=()=>{zoom=100;applyZoom();};window.addEventListener('resize',()=>{if(book)applyZoom();});
$('reader-help').onclick=()=>toast('單頁：左右滑動或 ← → 翻頁；右至左時 ← 是下一頁。長條：上下捲動。Esc 返回；放大後可拖曳捲動。');document.addEventListener('keydown',ev=>{if(!book||document.querySelector('dialog[open]'))return;if(ev.key==='Tab'){const targets=[...$('reader').querySelectorAll('button:not(:disabled),select,[tabindex="0"]')];const first=targets[0],last=targets.at(-1);if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last.focus();}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus();}return;}if(ev.key==='Escape'){ev.preventDefault();closeReader();return;}if(['INPUT','SELECT','TEXTAREA'].includes(ev.target.tagName))return;if(ev.key==='ArrowLeft'||ev.key==='ArrowRight'){ev.preventDefault();navigate(page+((ev.key==='ArrowLeft')===(direction==='rtl')?1:-1));}else if(ev.key==='Home'){ev.preventDefault();navigate(0);}else if(ev.key==='End'){ev.preventDefault();navigate(book.pages.length-1);}});
let touch=null;$('reader-stage').addEventListener('touchstart',ev=>{touch=ev.touches.length===1?{x:ev.touches[0].clientX,y:ev.touches[0].clientY}:null;},{passive:true});$('reader-stage').addEventListener('touchend',ev=>{if(!touch||!book||mode!=='page'||zoom>100)return;const t=ev.changedTouches[0],dx=t.clientX-touch.x,dy=t.clientY-touch.y;touch=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.7)navigate(page+((dx>0)===(direction==='rtl')?1:-1));},{passive:true});
$('search').oninput=renderCards;$('show-favorites').onclick=()=>{onlyFavorites=!onlyFavorites;renderCards();$('ranking').scrollIntoView();toast(onlyFavorites?'顯示收藏作品':'顯示全部十部作品');};$('sources-button').onclick=$('sources-bottom').onclick=()=>$('sources').showModal();$('sources-close').onclick=()=>$('sources').close();$('detail-close').onclick=()=>$('details').close();$('import-top').onclick=$('import-main').onclick=startImport;$('pick-files').onclick=()=>$('files').click();$('cancel-import').onclick=stopImport;$('import-dialog').addEventListener('cancel',stopImport);$('import-dialog').addEventListener('close',()=>{importToken++;$('pick-files').disabled=false;$('files').value='';});$('clear-data').onclick=()=>{if(!confirm('清除這個瀏覽器中的閱讀進度、收藏與設定？'))return;favorites.clear();progress={};mode='page';direction='rtl';try{localStorage.removeItem(storageKey);}catch{}renderCards();updateResume();toast('已清除本機閱讀資料。');};window.addEventListener('beforeunload',releaseLocal);renderCards();updateResume();
})();
